# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 18, 7, 24, 29, 448922, tzinfo=utc)),
        ),
    ]
